# Generated by Django 4.1.5 on 2023-01-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprinkler',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
