# Generated by Django 4.1.4 on 2023-01-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_sprinkler_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprinkler',
            name='codSprinkler',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
