# Generated by Django 4.1.4 on 2023-01-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_sprinkler_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprinkler',
            name='autoOff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sprinkler',
            name='autoOn',
            field=models.BooleanField(default=True),
        ),
    ]
