# Generated by Django 4.1.4 on 2023-01-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_sprinkler_autooff_sprinkler_autoon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprinkler',
            name='autoOff',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='autoOn',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
