# Generated by Django 4.1.4 on 2023-01-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_sprinkler_autooff_alter_sprinkler_autoon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprinkler',
            name='autoOff',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
