# Generated by Django 4.1.4 on 2023-01-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_sprinkler_autooff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprinkler',
            name='oldState',
            field=models.BooleanField(default=False),
        ),
    ]
