# Generated by Django 4.1.4 on 2023-01-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_sprinkler_oldstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
