# Generated by Django 4.1.4 on 2023-01-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
